version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        volumes:
            - ./src:/var/www/html
            - app

    db:
        image: mariadb
        ports:
        - "3306"
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8181:80"
        environment:
            - PMA_ARBITRARY=1

    composer:
        restart: 'no'
        image: composer/composer
        command:
        - install
        - dump-autoload
        volumes:
            - .:/app
